In [1]:
#Listing 2.7 from book.

import tensorflow as tf

sess = tf.InteractiveSession()

matrix = tf.constant([1,2]);
negMatrix = tf.neg(matrix);

result = negMatrix.eval();
print(result)
sess.close()



[-1 -2]


In [13]:
#Addition & Multiplication of two 3x3 matrix.

import tensorflow as tf

sess = tf.InteractiveSession()
matrix1 = tf.constant([[1,7,9],[3,2,1],[9,31,40]]);
matrix2 = tf.constant([[5,4,3],[1,1,1],[0,0,0]]);

print("Matrix1");
print(matrix1);
print("Matrix2");
print(matrix2);

#Addition.
addition_result = tf.add(matrix1,matrix2,name=None)
print("Addition of tensors");
print(addition_result.eval());

multiplication_result = tf.mul(matrix1,matrix2,name=None)
print();
print("Multiplication of tensors")
print(multiplication_result.eval())

sess.close()

# test_val_1 = 2;
# test_val_2 = 3
# print(tf.add(test_val_1,test_val_2,name="None"));


Matrix1
Tensor("Const_23:0", shape=(3, 3), dtype=int32)
Matrix2
Tensor("Const_24:0", shape=(3, 3), dtype=int32)
Addition of tensors
[[ 6 11 12]
 [ 4  3  2]
 [ 9 31 40]]

Multiplication of tensors
[[ 5 28 27]
 [ 3  2  1]
 [ 0  0  0]]


In [16]:
# Listing 2.9 from book

import tensorflow as tf

#Interactive Session Creation.
session = tf.InteractiveSession();

raw_data = [1.,2.,8.,-1,0.,5.5,6.,13];
spike = tf.Variable(False)
spike.initializer.run()

for i in range(1,len(raw_data)):
    if raw_data[i] - raw_data[i-1] > 5 :
        updater = tf.assign(spike, True)
        updater.eval()
    else:
        tf.assign(spike,False).eval();
    print("Spike",spike.eval());  
session.close()    

Spike False
Spike True
Spike False
Spike False
Spike True
Spike False
Spike True


In [ ]:
# Listing 2.9 from book

# import tensorflow as tf

# #Interactive Session Creation.
# # session = tf.InteractiveSession();

# raw_data = [1.,2.,8.,-1,0.,5.5,6.,13];
# with tf.Session() as sess:
#     spike = tf.Variable(False);
#     spike.initializer.run();
#     for i in range(1,len(raw_data)):
#         if raw_data[i] - raw_data[i-1] > 5:
#             updater = tf.assign(spike,True)

In [1]:
#Listing 2.10 from book.

import tensorflow as tf;
session = tf.InteractiveSession();

raw_data = [1.,2.,8.,-1,0.,5.5,6.,13];
# tf.initialize_all_variables()
spikes = tf.Variable([False] * len(raw_data), name='spikes');
spikes.initializer.run();

saver = tf.train.Saver()

for i in range(1,len(raw_data)):
    if raw_data[i] - raw_data[i-1] > 5:
        spikes_val = spikes.eval();
        spikes_val[i] = True;
        updater = tf.assign(spikes, spikes_val);
        updater.eval();

print(updater.eval());        
save_path = saver.save(session,"spikes.ckpt");
print("spikes data saved in file : %s" % save_path);

session.close()


[False False  True False False  True False  True]
spikes data saved in file : spikes.ckpt


In [1]:
#Listing 2.11 from book.
import tensorflow as tf;
session = tf.InteractiveSession()

spikes = tf.Variable([False]*8, name='spikes');
# spikes.initializer.run();
saver = tf.train.Saver();

saver.restore(session, "spikes.ckpt");
print(spikes.eval());

session.close()

[False False  True False False  True False  True]


In [1]:
import tensorflow as tf 
import numpy as np

raw_data = np.random.normal(10,1,100);

alpha = tf.constant(0.05);
curr_value = tf.placeholder(tf.float32);
prev_avg = tf.Variable(0.);
update_avg = alpha * curr_value + (1 - alpha) * prev_avg;

avg_hist = tf.scalar_summary("running average", update_avg);
value_hist = tf.scalar_summary("incoming values", curr_value);
merged = tf.merge_all_summaries();
writer = tf.train.SummaryWriter("./logs");
init = tf.initialize_all_variables();

with tf.Session() as sess:
    sess.run(init);
    for i in range(len(raw_data)):
        summary_str, curr_avg = sess.run([merged, update_avg], feed_dict={curr_value:raw_data[i]})
        sess.run(tf.assign(prev_avg, curr_avg))
        print(raw_data[i], curr_avg);
        writer.add_summary(summary_str, i)

9.57328415982 0.478664
10.6404655193 0.986754
8.80910165217 1.37787
10.2744617281 1.8227
9.48722764959 2.20593
9.57885239813 2.57457
9.96709051518 2.9442
10.5328994454 3.32363
10.2602910193 3.67047
9.81305124232 3.9776
7.96129004288 4.17678
11.4301355083 4.53945
10.7308531709 4.84902
9.66779914094 5.08996
10.0372881436 5.33732
8.26982253303 5.48395
9.36575529221 5.67804
10.7614823314 5.93221
10.9610091108 6.18365
9.9880462642 6.37387
9.91161701834 6.55076
10.5797868126 6.75221
9.38005746617 6.8836
9.67967767807 7.0234
11.6452523867 7.2545
10.9866022944 7.4411
10.2875050472 7.58342
10.6475058289 7.73663
10.0299189545 7.85129
9.23476313849 7.92046
11.5188365439 8.10038
10.4204236063 8.21638
9.7651172874 8.29382
10.4698989063 8.40263
10.4433965785 8.50466
9.46038477542 8.55245
11.4144847167 8.69555
10.0124238558 8.7614
10.1149126495 8.82907
9.680342334 8.87163
10.8605269518 8.97108
10.4792333892 9.04649
9.72982181282 9.08065
9.53649226081 9.10345
10.6165484663 9.1791
9.78026495436 9.20916